app/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home , name='home'),
    path(_('contact/'), views.contact , name='contact'),
    path(_('about/'), views.about , name='about'),
    path(_('education/'), views.education , name='education'),
    path(_('skills/'), views.skills , name='skills'),
    path(_('projects/'), views.projects , name='projects'),
]

eisa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns=[
    path('rosetta/', include('rosetta.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('app.urls', namespace='app')),
    prefix_default_language=True,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/about.html
{% extends '_base.html' %}
{% load i18n static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/about.min.css' %}">
{% endblock css %}


{% block content %}
{{ block.super }}
<div class="wrapper">
  <h1>{% translate 'About Me' %}</h1>
  <div class="bio" {% if bidi %} style="text-align:right;" dir="rtl" {% endif %}>
    {% url 'app:skills' as path %}
     {% blocktranslate  %}
     Hello, nice to meet you!
     <br><br>
    Let me tell you a little about my story. I am from Iran, a South-Asia country that is going through a tough time.
    <br>I have have learned different skills you can check by clicking on
    <a href="{{path}}">Skills</a> link.
      I love programming, it is amazing to me how I am able to transform abstract ideas
     into software, making the complex simple .I can take care of all your web development stuff and enjoy sharing my knowledge as well as creating and innovating.
     <br><br>
     Now just keep clicking, and get to know me better as you go!
     {% endblocktranslate %}
  </div>
</div>

{% endblock content %}



{% block js %}
{% endblock js %}

templates/app/carousel.html
{% load static my_filters %}
<div class="CSSgal">

  {% with  images=p.images.all %}
  {% with  length=images|length %}



  {% for i in images %}
    <s class="{% if forloop.first %}current{% endif %}" id="s{{forloop.counter}}{{p.pk}}"></s>
  {% endfor %}

  <div class="slider">
    {% for img in images %}
      <div style="background-image: url({{img.image.url}})"></div>
    {% endfor %}
  </div>


  <div class="bullets">
{% if length > 1 %}
     {% for i in images %}
      {% if forloop.counter < 6 %}
        <a class="{% if forloop.first %}current{% endif %}" href="" onclick="link2slider(this);return false;"
                data-target="s{{forloop.counter}}{{p.pk}}">{{forloop.counter}}</a>
      {% endif %}
     {% endfor %}
{% endif %}
  </div>


  {% endwith %}
  {% endwith %}

</div>

templates/app/contact.html
{% extends '_base.html' %}
{% load static i18n my_filters %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/contact.min.css' %}">
{% endblock css %}


{% block content %}
{{ block.super }}
<div class="envelope">
  <div class="envelope-cap"></div>
  <div class="latter-form" {% if bidi %} style="text-align:right;" dir="rtl" {% endif %}>
    <form class="" action="" method="post">
      {% csrf_token%}
      <p>{% translate 'Hi,' %}</p>
      <span>{% translate 'I am' %}</span>
      {% if form.full_name.errors %}
        {{form.full_name|addClass:'error'}}
      {% else %}
        {{form.full_name}}
      {% endif %}
      <span>{% translate 'you can mail me at' %}</span>
      {% if form.sender_mail.errors %}
        {{form.sender_mail|addClass:'error'}}
      {% else %}
        {{form.sender_mail}}
      {% endif %}
      <br/><span>{% translate ', or call me at' %}</span>
      {% if form.sender_phone.errors %}
        {{form.sender_phone|addClass:'error'}}
      {% else %}
        {{form.sender_phone}}
      {% endif %}
      <span>{% translate 'I would like to inform you that:' %}</span>
      {% if form.content.errors %}
        {{form.content|addClass:'error'}}
      {% else %}
        {{form.content}}
      {% endif %}
      <p class="thanks">{% translate 'Thank You' %}</p>
      <div class="btn-wrapper" {% if bidi %} style="justify-content:left !important;" dir="ltr"{% endif %}>
        <button class="latter-btn">{% translate 'Send' %}</button>
      </div>

    </form>
  </div>
</div>
{% endblock content %}



{% block js %}
<script type="text/javascript" src="{% static 'js/app/contact.js' %}" defer></script>
{% endblock js %}

templates/app/education.html
{% extends '_base.html' %}
{% load i18n static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/education.min.css' %}">
{% endblock css %}


{% block content %}
{{ block.super }}
<div class="wrapper">
  <h1>{% translate 'Education' %}</h1>
  <h3>{% translate 'University' %}</h3>
  <div class=" education University">
    <span>{% translate 'Hakim Sabzevari University (2012-2016)' %}</span>
    <img class="anabin" title="this image be derived of anabin.kmk.org "
       src="{% if request.LANGUAGE_CODE == 'de' %}{% static 'img/anabin-de-univ-watermarked.png' %}{% else %}{% static 'img/anabin-en-univ-watermarked.png' %}{% endif %}"
       alt="derived of anabin.kmk.org">
  </div>
  <h3>{% translate 'Field and Degree' %}</h3>
  <div class="education field">
    <span>  {% translate 'Bachelor in Electrical Engineeing' %}</span>
    <img class="anabin" title="this image be derived of anabin.kmk.org "
      alt="this image be derived of anabin.kmk.org"
      src="{% if request.LANGUAGE_CODE == 'de' %}{% static 'img/anabin-de-watermark.png' %}{% else %}{% static 'img/anabin-en-watermarked.png' %}{% endif %}">
  </div>
</div>

{% endblock content %}



{% block js %}
{% endblock js %}

templates/app/home.html
{% extends '_base.html' %}
{% load i18n static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/home.min.css' %}">
{% endblock css %}


{% block content %}
<div class="section">

  <div class="row top">
    <div class="line-left">
      <a href="{% url 'app:contact' %}" class="two">
        {% translate 'Contact' %}
      </a>
      <a href="{% url 'app:education' %}" class="one">
        {% translate 'Education' %}
      </a>
    </div>

    <a href="{% url 'app:skills' %}" class="three">
      {% translate 'Skills' %}
    </a>
    <div class="line-right">
      <a href="{% url 'app:projects' %}" class="four">
        {% translate 'Projects' %}
      </a>
      <a href="{% url 'app:about' %}" class="five">
        {% translate 'About me' %}
      </a>
    </div>

  </div>

  <div class="row wrapper-image">
    <img src="{% static 'img/eisa-91.jpg' %}" alt="" class="img">
  </div>


  <div class="full-name">
    {% translate 'Eisa Nahardani' %}
  </div>

  <div class="share">
    <div class="social-buttons">
      <a href="https://github.com/EasaNahardani" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://stackoverflow.com/users/18005739/eisa-nahardani?tab=profile" target="_blank"><i class="fab fa-stack-overflow"></i></a>
      <a href="{% url 'app:contact' %}" ><i class="fa fa-envelope"></i></a>
      <a href="https://linkedin.com/in/eisa-nahardani" target="_blank"><i class="fa fa-linkedin-square"></i></a>
      <a href="https://mail.google.com/mail/?view=cm&fs=1&to=92developer92@gmail.com" target="_blank"><i>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="25px" height="25px" viewBox="0 0 25 25" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:nonzero;fill:#4a5073;fill-opacity:1;" d="M 10.84375 0.121094 C 6.773438 0.632812 2.914062 3.480469 1.167969 7.261719 C -0.34375 10.53125 -0.34375 14.492188 1.167969 17.761719 C 2.324219 20.25 4.59375 22.566406 7.0625 23.742188 C 11.230469 25.746094 16.238281 25.300781 19.863281 22.597656 C 26.199219 17.871094 26.769531 8.863281 21.0625 3.449219 C 18.304688 0.824219 14.679688 -0.355469 10.84375 0.121094 Z M 18.605469 8.140625 C 18.785156 8.363281 18.792969 8.683594 18.773438 12.644531 L 18.738281 16.925781 L 18.472656 17.136719 C 18.273438 17.304688 18.070312 17.347656 17.695312 17.328125 L 17.183594 17.292969 L 17.125 13.769531 L 17.070312 10.253906 L 15.515625 11.386719 C 14.65625 12.011719 13.625 12.753906 13.222656 13.046875 L 12.476562 13.566406 L 10.1875 11.898438 C 8.929688 10.976562 7.875 10.230469 7.839844 10.230469 C 7.808594 10.230469 7.785156 11.832031 7.785156 13.789062 L 7.785156 17.347656 L 7.285156 17.347656 C 6.894531 17.347656 6.707031 17.28125 6.503906 17.070312 L 6.226562 16.804688 L 6.226562 12.644531 C 6.226562 8.597656 6.238281 8.472656 6.460938 8.183594 C 6.894531 7.628906 7.140625 7.738281 9.71875 9.609375 C 11.011719 10.542969 12.175781 11.375 12.300781 11.453125 C 12.523438 11.589844 12.710938 11.476562 14.800781 9.953125 C 16.046875 9.042969 17.238281 8.183594 17.460938 8.039062 C 17.90625 7.730469 18.292969 7.773438 18.605469 8.140625 Z M 18.605469 8.140625 "/>
</g>
</svg>
</i>
</a>
    </div>
  </div>

</div>
{% endblock content %}

templates/app/project_card.html
{% load static i18n  my_filters %}
<div class="col-md-6 col-lg-6 col-xl-4 proj">
  <div class="card card-profile">
    <div class="card-header" >
      {% include 'app/carousel.html' %}
    </div>
    <div class="card-body" data-url="{{p.url}}">
      <h5 class="title" >{{p.title}}</h5>
    </div>
    <div class="line"></div>
    {% if p.language %}
      <span class="lang">{{p.language}}</span>
      <div class="tech">
        {% for t in p.technologies|splitter %}
          <span>{{t}}</span>
        {% endfor %}
      </div>
      {% else %}
        <div class="description">
          {{p.description|safe|truncatechars:200}}
        </div>
      {% endif %}
    <div class="card-footer" {% if bidi %} dir="rtl" {% endif %}>
      {% if p.status == 'published' %}
      <div class="publish">
        <span>{% translate 'Publication Date' %}</span>
        <span class="date" dir="ltr" data-date="{{p.publish.isoformat}}">{{p.publish|date:"Y F"}}</span>
      </div>
      {% else %}
        <span class="soon" dir="ltr">{% translate 'Coming soon..' %}</span>
      {% endif %}
    </div>
  </div>

</div>

templates/app/projects.html
{% extends '_base.html' %}
{% load i18n static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/projects.min.css' %}">
<link rel="stylesheet" href="{% static 'css/app/carousel.min.css' %}">
{% endblock css %}


{% block content %}
{{ block.super }}
<div class="wrapper">
  <h1>{% translate 'Projects' %}</h1>
  <div class="contents">
    <div class="category-wrapper">
      <div class="application category {% if not '?' in request.get_full_path %}active{% endif %}" title="Mobile Applications & Web Applications" data-category="application">
        <span>{% translate 'Apps' %}</span>
      </div>
        <div class="articles category {% if 'article' in request.get_full_path %}active{% endif %} " title="Articles" data-category="article">
          <span>{% translate 'Articles' %}</span>
        </div>
        <div class="libraries category {% if 'library' in request.get_full_path %}active{% endif %}" title="3th-party packages and libraries" data-category="library">
          <span>{% translate 'Libraries' %}</span>
        </div>
    </div>

  </div>
  <div class="projects row">
    {% for p in projects %}
      {% include 'app/project_card.html' %}
    {% endfor %}
  </div>
</div>

{% endblock content %}



{% block js %}
<script type="text/javascript" src="{% static 'js/app/projects.min.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/app/carousel.min.js' %}" defer></script>
{% endblock js %}

templates/app/skills.html
{% extends '_base.html' %}
{% load i18n  static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/app/skills.min.css' %}">
{% endblock css %}


{% block content %}
{{ block.super }}
<div class="wrapper">
  <h1>{% translate 'Skills' %}</h1>
  <div class="row progresses">

  {% for s in skills %}
  <div class="progress-wrapper">
    <div class="progress ">
      <svg class="progress-circle" width="200px" height="200px" xmlns="http://www.w3.org/2000/svg">
        <circle class="progress-circle-back"
            cx="80" cy="80" r="74"></circle>
        <circle class="progress-circle-prog"
                cx="80" cy="80" r="74"></circle>
      </svg>
     <div class="progress-text" data-progress="{{s.level}}">0%</div>
    </div>
    <span>{{s.name}}</span>
  </div>
  {% endfor %}

  </div>
</div>

{% endblock content %}



{% block js %}
<script type="text/javascript" src="{% static 'js/app/skills.js' %}" defer></script>
{% endblock js %}