app/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home , name='home'),
    path(_('contact/'), views.contact , name='contact'),
    path(_('about/'), views.about , name='about'),
    path(_('education/'), views.education , name='education'),
    path(_('skills/'), views.skills , name='skills'),
    path(_('projects/'), views.projects , name='projects'),
]

eisa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns=[
    path('rosetta/', include('rosetta.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('app.urls', namespace='app')),
    prefix_default_language=True,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_base.html
<!--
=========================================================
* Eisa Nahardani -- Web Developer -- 92developer92@gmail.com
======================================================
-->
{% load i18n static my_filters %}
<!DOCTYPE html>
{% get_current_language_bidi as bidi %}
<html lang="en" class="notranslate" translate="no">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->

<title>
  {% block title %}Eisa Nahardani{% endblock %}
</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="">
<meta name="author" content="Eisa Nahardani">
<meta name="description" content="I have have learned different skills you can check by clicking on Skills link.
  I love programming, it is amazing to me how I am able to transform abstract ideas into software, making the complex simple
   .I can take care of all your web development stuff and enjoy sharing my knowledge as well as creating and innovating.">
<meta name="keywords" content="Eisa Nahardani, عیسی نهاردانی, web developer, عیسی نهالدانی, back-end developer, web programmer, django programmer, python, django,
   وبسایت شخصی عیسی نهاردانی" />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="">
<meta property="og:title" content="Eisa Nahardani-Web Developer">
<meta property="og:description" content="I have have learned different skills you can check by clicking on Skills link. I love programming,
   it is amazing to me how I am able to transform abstract ideas into software,
   making the complex simple .I can take care of all your web development stuff and enjoy sharing my knowledge as well as creating and innovating.">
<meta property="og:image" content="">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="">
<meta property="twitter:title" content="Eisa Nahardani-Web Developer">
<meta property="twitter:description" content="I have have learned different skills you can check by clicking on Skills link.
  I love programming, it is amazing to me how I am able to transform abstract ideas into software, making the complex simple .
  I can take care of all your web development stuff and enjoy sharing my knowledge as well as creating and innovating.">
<meta property="twitter:image" content="">

<!-- Favicon -->
<!--
<link rel="apple-touch-icon" sizes="120x120" href="/static/assets/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon/favicon-16x16.png">
<link rel="manifest" href="/static/assets/img/favicon/site.webmanifest">
<link rel="mask-icon" href="/static/assets/img/favicon/safari-pinned-tab.svg" color="#ffffff">-->
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static 'css/core/bootstrap.min.css' %}">

<!-- FA Icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
       crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static '/css/_base.min.css' %}">

{% block css %}

{% endblock css %}

</head>
{% with current_lang=request.LANGUAGE_CODE %}
<body  {% if current_lang == 'fa' %} style="font-family:fadigits, sans;"{% elif current_lang == 'de' %}style='font-family:"Walbaum-Bold";'{% else %}style="font-family:cursive;"{% endif %}>

  {% if messages %}
    <ul class="messages">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %} {% if bidi %} dir="rtl" {% endif %}>
        {{ message|safe }}
        <div class="close-wrapper">
          <button  class="close"></button>
        </div>
      </li>
    {% endfor %}
    </ul>
  {% endif %}


{% get_available_languages as LANGUAGES %}

  <ul  class="lang-switcher">
    {% for language in LANGUAGES %}
     {% with lang_code=language.0 %}
      <li class="{% if lang_code == current_lang %}current{% else %}other{% endif %}"
          title="{% if lang_code == current_lang %}{% translate 'Click on the links on the rigth to see other languages' %}{% else %}{{ lang_code|language_name_local }}{% endif %}">
           <a {% if not lang_code == current_lang %}href="{{request.get_full_path|translated_url:lang_code}}"{% else %}href="javascript:void(0);"{% endif %}">
             {% include lang_code|add:"-flag.html" %}
          </a>
      </li>
      {% endwith %}
    {% endfor %}
  </ul>
  {% endwith %}


    {% block content %}
    <div class="back-btn">
      <a href="{% url 'app:home' %}">
        {% translate 'Home' %}
      </a>
    </div>
    {% endblock content %}


    {% include './scripts.html' %}

    {% block js %}
    {% endblock js %}

</body>
</html>

templates/de-flag.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="45px" height="45px" viewBox="0 0 45 45" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 43.128906 15.226562 L 2.121094 15.226562 C 5.113281 6.789062 13.164062 0.75 22.625 0.75 C 32.085938 0.75 40.136719 6.789062 43.128906 15.226562 Z M 43.128906 15.226562 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(86.666667%,0%,0%);fill-opacity:1;" d="M 44.375 22.5 C 44.375 25.078125 43.925781 27.554688 43.101562 29.847656 L 2.148438 29.847656 C 1.324219 27.554688 0.875 25.078125 0.875 22.5 C 0.875 19.949219 1.3125 17.5 2.121094 15.226562 L 43.128906 15.226562 C 43.933594 17.5 44.375 19.949219 44.375 22.5 Z M 44.375 22.5 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(100%,80.784314%,0%);fill-opacity:1;" d="M 43.101562 29.847656 C 40.089844 38.246094 32.058594 44.25 22.625 44.25 C 13.191406 44.25 5.160156 38.246094 2.148438 29.847656 Z M 43.101562 29.847656 "/>
</g>
</svg>

templates/en-flag.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="45px" height="45px" viewBox="0 0 45 45" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 20.550781 0.0898438 C 20.265625 0.121094 19.574219 0.226562 19.019531 0.316406 L 18 0.480469 L 18 18 L 0.480469 18 L 0.285156 19.003906 C 0.015625 20.339844 0.015625 24.660156 0.285156 25.996094 L 0.480469 27 L 18 27 L 18 44.519531 L 19.019531 44.714844 C 20.339844 44.984375 24.660156 44.984375 25.996094 44.714844 L 27 44.519531 L 27 27 L 44.519531 27 L 44.714844 25.996094 C 44.835938 25.394531 44.910156 23.953125 44.910156 22.5 C 44.910156 21.046875 44.835938 19.605469 44.714844 19.003906 L 44.519531 18 L 27 18 L 27 0.496094 L 26.144531 0.316406 C 25.246094 0.136719 21.480469 -0.015625 20.550781 0.0898438 Z M 20.550781 0.0898438 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 13.425781 1.921875 C 11.671875 2.730469 10.378906 3.480469 9.046875 4.46875 C 7.828125 5.386719 4.949219 8.191406 4.949219 8.460938 C 4.949219 8.550781 7.214844 9.75 9.976562 11.144531 L 15 13.648438 L 15 7.5 C 15 2.671875 14.953125 1.351562 14.820312 1.351562 C 14.714844 1.363281 14.085938 1.621094 13.425781 1.921875 Z M 13.425781 1.921875 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 30 7.5 L 30 13.648438 L 35.023438 11.144531 C 37.785156 9.75 40.050781 8.550781 40.050781 8.460938 C 40.050781 8.144531 36.886719 5.128906 35.578125 4.199219 C 34.351562 3.328125 30.628906 1.351562 30.195312 1.351562 C 30.046875 1.351562 30 2.535156 30 7.5 Z M 30 7.5 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 36 12.449219 L 30.976562 14.984375 L 34.199219 15 L 37.425781 15 L 42.613281 12.421875 L 42.179688 11.65625 C 41.28125 10.078125 41.175781 9.898438 41.101562 9.914062 C 41.054688 9.914062 38.761719 11.054688 36 12.449219 Z M 36 12.449219 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 1.800781 13.738281 C 1.546875 14.371094 1.363281 14.910156 1.394531 14.941406 C 1.425781 14.984375 2.761719 14.984375 4.363281 14.96875 L 7.273438 14.925781 L 4.964844 13.753906 C 3.703125 13.125 2.578125 12.601562 2.476562 12.601562 C 2.371094 12.601562 2.070312 13.109375 1.800781 13.738281 Z M 1.800781 13.738281 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 4.980469 31.289062 C 2.519531 32.503906 2.414062 32.578125 2.566406 32.894531 C 2.714844 33.179688 3.734375 34.933594 3.839844 35.070312 C 3.855469 35.101562 6.148438 33.976562 8.941406 32.566406 L 14.023438 30.015625 L 10.800781 30.015625 L 7.558594 30 Z M 4.980469 31.289062 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 37.664062 30.058594 C 37.695312 30.089844 38.820312 30.660156 40.171875 31.335938 L 42.613281 32.566406 L 43.035156 31.621094 C 43.273438 31.09375 43.515625 30.523438 43.558594 30.328125 L 43.664062 30 L 40.636719 30 C 38.96875 30 37.636719 30.03125 37.664062 30.058594 Z M 37.664062 30.058594 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 9.945312 33.871094 C 7.199219 35.25 4.949219 36.449219 4.949219 36.539062 C 4.949219 36.796875 7.785156 39.585938 8.925781 40.441406 C 9.511719 40.875 10.484375 41.519531 11.101562 41.878906 C 12.269531 42.554688 14.566406 43.648438 14.851562 43.648438 C 14.953125 43.648438 15 41.65625 15 37.5 C 15 34.109375 14.984375 31.351562 14.96875 31.363281 C 14.941406 31.363281 12.675781 32.488281 9.945312 33.871094 Z M 9.945312 33.871094 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 30 37.5 C 30 41.65625 30.046875 43.648438 30.148438 43.648438 C 30.433594 43.648438 32.730469 42.554688 33.898438 41.878906 C 34.515625 41.519531 35.503906 40.875 36.074219 40.441406 C 37.214844 39.585938 40.050781 36.796875 40.050781 36.539062 C 40.050781 36.449219 37.785156 35.25 35.023438 33.855469 L 30 31.351562 Z M 30 37.5 "/>
</g>
</svg>

templates/england-flag.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="45px" height="45px" viewBox="0 0 45 45" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 20.550781 0.0898438 C 20.265625 0.121094 19.574219 0.226562 19.019531 0.316406 L 18 0.480469 L 18 18 L 0.480469 18 L 0.285156 19.003906 C 0.015625 20.339844 0.015625 24.660156 0.285156 25.996094 L 0.480469 27 L 18 27 L 18 44.519531 L 19.019531 44.714844 C 20.339844 44.984375 24.660156 44.984375 25.996094 44.714844 L 27 44.519531 L 27 27 L 44.519531 27 L 44.714844 25.996094 C 44.835938 25.394531 44.910156 23.953125 44.910156 22.5 C 44.910156 21.046875 44.835938 19.605469 44.714844 19.003906 L 44.519531 18 L 27 18 L 27 0.496094 L 26.144531 0.316406 C 25.246094 0.136719 21.480469 -0.015625 20.550781 0.0898438 Z M 20.550781 0.0898438 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 13.425781 1.921875 C 11.671875 2.730469 10.378906 3.480469 9.046875 4.46875 C 7.828125 5.386719 4.949219 8.191406 4.949219 8.460938 C 4.949219 8.550781 7.214844 9.75 9.976562 11.144531 L 15 13.648438 L 15 7.5 C 15 2.671875 14.953125 1.351562 14.820312 1.351562 C 14.714844 1.363281 14.085938 1.621094 13.425781 1.921875 Z M 13.425781 1.921875 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 30 7.5 L 30 13.648438 L 35.023438 11.144531 C 37.785156 9.75 40.050781 8.550781 40.050781 8.460938 C 40.050781 8.144531 36.886719 5.128906 35.578125 4.199219 C 34.351562 3.328125 30.628906 1.351562 30.195312 1.351562 C 30.046875 1.351562 30 2.535156 30 7.5 Z M 30 7.5 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 36 12.449219 L 30.976562 14.984375 L 34.199219 15 L 37.425781 15 L 42.613281 12.421875 L 42.179688 11.65625 C 41.28125 10.078125 41.175781 9.898438 41.101562 9.914062 C 41.054688 9.914062 38.761719 11.054688 36 12.449219 Z M 36 12.449219 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 1.800781 13.738281 C 1.546875 14.371094 1.363281 14.910156 1.394531 14.941406 C 1.425781 14.984375 2.761719 14.984375 4.363281 14.96875 L 7.273438 14.925781 L 4.964844 13.753906 C 3.703125 13.125 2.578125 12.601562 2.476562 12.601562 C 2.371094 12.601562 2.070312 13.109375 1.800781 13.738281 Z M 1.800781 13.738281 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 4.980469 31.289062 C 2.519531 32.503906 2.414062 32.578125 2.566406 32.894531 C 2.714844 33.179688 3.734375 34.933594 3.839844 35.070312 C 3.855469 35.101562 6.148438 33.976562 8.941406 32.566406 L 14.023438 30.015625 L 10.800781 30.015625 L 7.558594 30 Z M 4.980469 31.289062 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#cc142c;fill-opacity:1;" d="M 37.664062 30.058594 C 37.695312 30.089844 38.820312 30.660156 40.171875 31.335938 L 42.613281 32.566406 L 43.035156 31.621094 C 43.273438 31.09375 43.515625 30.523438 43.558594 30.328125 L 43.664062 30 L 40.636719 30 C 38.96875 30 37.636719 30.03125 37.664062 30.058594 Z M 37.664062 30.058594 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 9.945312 33.871094 C 7.199219 35.25 4.949219 36.449219 4.949219 36.539062 C 4.949219 36.796875 7.785156 39.585938 8.925781 40.441406 C 9.511719 40.875 10.484375 41.519531 11.101562 41.878906 C 12.269531 42.554688 14.566406 43.648438 14.851562 43.648438 C 14.953125 43.648438 15 41.65625 15 37.5 C 15 34.109375 14.984375 31.351562 14.96875 31.363281 C 14.941406 31.363281 12.675781 32.488281 9.945312 33.871094 Z M 9.945312 33.871094 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:#04247c;fill-opacity:1;" d="M 30 37.5 C 30 41.65625 30.046875 43.648438 30.148438 43.648438 C 30.433594 43.648438 32.730469 42.554688 33.898438 41.878906 C 34.515625 41.519531 35.503906 40.875 36.074219 40.441406 C 37.214844 39.585938 40.050781 36.796875 40.050781 36.539062 C 40.050781 36.449219 37.785156 35.25 35.023438 33.855469 L 30 31.351562 Z M 30 37.5 "/>
</g>
</svg>

templates/germany-flag.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="45px" height="45px" viewBox="0 0 45 45" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 43.128906 15.226562 L 2.121094 15.226562 C 5.113281 6.789062 13.164062 0.75 22.625 0.75 C 32.085938 0.75 40.136719 6.789062 43.128906 15.226562 Z M 43.128906 15.226562 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(86.666667%,0%,0%);fill-opacity:1;" d="M 44.375 22.5 C 44.375 25.078125 43.925781 27.554688 43.101562 29.847656 L 2.148438 29.847656 C 1.324219 27.554688 0.875 25.078125 0.875 22.5 C 0.875 19.949219 1.3125 17.5 2.121094 15.226562 L 43.128906 15.226562 C 43.933594 17.5 44.375 19.949219 44.375 22.5 Z M 44.375 22.5 "/>
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(100%,80.784314%,0%);fill-opacity:1;" d="M 43.101562 29.847656 C 40.089844 38.246094 32.058594 44.25 22.625 44.25 C 13.191406 44.25 5.160156 38.246094 2.148438 29.847656 Z M 43.101562 29.847656 "/>
</g>
</svg>

templates/scripts.html
{% load static %}
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" ></script>
<script src="{% static 'js/core/popper.min.js' %}" ></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" defer></script>

<!-- messages framwork --->
<script src="{% static 'js/_base.js' %}" defer></script>